### ISSUE TITLE
better shared password management

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1019]
## Background Information

While we want to use single sign-on as much as possible (https://github.com/18F/tts-tech-portfolio/issues/931), there are some (unfortunate) cases where credentials need to be shared. AWS root credentials are an example (cc https://github.com/18F/tts-tech-portfolio/issues/666). KeePassXC + Google Drive File Stream has proved to be fragile.

Ideal side benefit of this is having better password management for individuals in TTS, though that is a secondary concern.

## Implementation Steps
- [ ] Market research completed
- [ ] IT Standards request submitted

## Acceptance Criteria

- [ ] We have an IT Standards request submitted for a password management tool

**Comment by afeld** [comment]
See email thread `[DevOps-Today] Question regarding use of Credential Managers`.
