### ISSUE TITLE
Add an automated secrets scan across TTS repos

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1025]
## Background Information

As part of the existing scanning and notification process for https://github.com/18F/tts-tech-portfolio/tree/master/inspector#usage. This issue is to track the additional feature of conducting a [gitleaks](https://github.com/zricethezav/gitleaks) scan of repos and report the results for any secrets detected at the same time as the dependabot to notify in the same slack channels.

https://github.com/GSA/odp-code-repository-commit-rules/blob/master/gitleaks/rules.toml

## Implementation Steps
- [ ] Run it manually as a simple script to review results with the team (decide from here to close issue or pursue this further)
- [ ] Add setup/run steps to docs
- [ ] Add a node hook to run gitleaks and return results per repo (Ideally concurrently or as a bulk report parsed per repo; how ever is easiest while considering github API rate limiting)

## Acceptance Criteria

- [ ] Determine if the results are too noisy - meaning its too noisy and/or too many false positives (to make it worth running at intervals vs as a manual one time/ quarterly audit.
- [ ] Gitleaks scan is conducted and report/results per repo are concat with the single post inspector sends.

**Comment by JJediny** [comment]
Here are past results, all of which's findings were communicated to the repositories owners ~9 months ago. Posting as an example of the results returned
[gitleaks-output.json.zip](https://github.com/18F/tts-tech-portfolio/files/5592197/gitleaks-output.json.zip)

**Comment by JJediny** [comment]
No longer needed as Secret Scanner is run at the org level now - https://github.com/orgs/GSA-TTS/security/alerts/secret-scanning?query=is%3Aclosed
