### ISSUE TITLE
Screaming Frog - Status

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [GSA-TTS/tts-tech-operations#1104]
## Background Information

Screaming Frog's GEAR approval expired on 4/1/2020. The program still needs to use this tool. There are no alternatives approved in GEAR.

## Implementation Steps
- [ ] Submit a new software request: [2021-94575](https://gsa.my.salesforce.com/a1Zt0000000oQFb)
- [ ] Ensure the request goes through the complete process

## Acceptance Criteria

- [ ] Screaming Frog is updated in GEAR with a current approval authorization date
