### ISSUE TITLE
ensure greater consistency of technology decisions for new systems

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1109]
## Background Information

We've had a few cases recently where some plans for custom software ended up being a surprise:

- Challenge.gov using Elixir
- GIVE using Java
- GIVE and Forms as a Service planning to use AWS directly

These design decisions aren't inherently bad, but they:

- Deviate from our recommended [languages](https://engineering.18f.gov/language-selection/)/[infrastructure](https://before-you-ship.18f.gov/infrastructure/)
- Are contrary to our goals around greater unification / less silo-ing of infrastructure (https://github.com/18F/tts-tech-portfolio/issues/827) and staff (https://github.com/18F/tts-tech-portfolio/issues/1050)

Therefore, those deviations should be things where everyone understands the tradeoffs and are choices we are making deliberately. (Example: "We are using this other language because we think it would make sense for TTS to grow experience in it.")

The documentation exists (linked above), so either:

- Folks making the technical decisions aren't aware of it
- It's not clear/explicit enough
- They don't adequately capture our range of technical needs

Architecture reviews are one way to solve this, such as through [the Digital Council's forthcoming new site review process](https://trello.com/c/SKsP9f67/46-site-launch-checklist).

The flip side of all this, of course, is that we don't want to introduce _too_ much friction. Will be a balance.

## Implementation Steps
- [ ] Lay out pros and cons
- [ ] Lay out what this could look like, process and personnel-wise
- [ ] Ask for feedback from TTS broadly

## Acceptance Criteria

- [ ] We have a decision on how to ensure new systems are in line with TTS-wide technical expectations/goals

**Comment by afeld** [comment]
This goes hand in hand with architecture reviews: https://github.com/18F/tts-tech-portfolio/issues/1169

**Comment by JJediny** [comment]
Devtools is looking at programming language out of scope for tech operations
