### ISSUE TITLE
Blog Post: Value of Stormdraining

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1263]
## Background Information

https://docs.google.com/spreadsheets/d/1ENJFQXtFZfkCkX0f_r8q_u3Pz2qta8skwU_6fvXI_cE/edit#gid=0

## Implementation Steps
- [ ] Brain dumb bullet points to include in blog post
- [ ] Draft Blog Post styled writeup on the activity and the value of conducting one

## Acceptance Criteria

- [ ] Determine where to share it and do so

**Comment by JJediny** [comment]
Will reopen if needed
