### ISSUE TITLE
Create a TTS FIDO key equipment management process

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1274]
## Background Information

TTS has previously purchased a set of 50 yubikeys for the login program, who have a number going unused/issued. As required by GSA IT policy, in order to access Google's Cloud Platform tied to GSA's google suite, account verification requires a titan key. We will need to purchase a number of these. 

Given we have an ongoing need, we should formalize the management and distribution, and equipment tracking of these assets.

## Implementation Steps
- [ ] Determine who can hold and distribute these assets
- [ ] Determine how to track and inventory
- [ ] Determine how TTS employees and contractors can request them
- [ ] PeopleOps tracks these as part of offboarding

## Acceptance Criteria

- [ ] TTS has a handbook page off of equipment for getting a GFE issued FIDO key formalizing the request process

**Comment by JJediny** [comment]
We are no longer involved in the provisioning of inventory we only performed a 1 time assisted acq to make the the intial purchase
