### ISSUE TITLE
Document the GCP and Azure Account Creation Process

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1297]
## Background Information

Now that we have GCP and Azure integrated with GSA's Active Directory and Gsuite

## Implementation Steps
- [x] GCP Account creation Documentation updated
- [x] Azure Account creation Documentation updated
- [ ] Make @afeld user with same billing ownership

## Acceptance Criteria

- [ ] GCP and Azure Account process and tested by @afeld

**Comment by afeld** [comment]
Part of https://github.com/18F/tts-tech-portfolio/issues/162.
