### ISSUE TITLE
Common Controls:  GitHub

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1310]
[**Worksheet**](https://docs.google.com/spreadsheets/d/16do7PKupIoGxivxgcJWnM7rQ90ny90A-l_KJCMnErb4/edit#gid=963344570)

## Background Information

All systems in TTS use GitHub for source code hosting, if not other things. We can provide a boilerplate set of control narratives that can be inherited/copied into SSPs.

## Implementation Steps
- [ ] Pull GitHub-related control narratives into worksheet
   - [x] Touchpoints
   - [x] data.gov
   - [ ] cloud.gov
   - [ ] login.gov
- [ ] Create consolidated version of each control narrative
- [ ] Publish
- [ ] Notify TTS system owners to have them incorporate

## Acceptance Criteria

- [ ] We have an initial set of control narratives around GitHub we think apply to most systems in TTS

**Comment by afeld** [comment]
cc https://github.com/18F/tts-tech-portfolio/issues/1249

**Comment by JJediny** [comment]
Being implemented here https://github.com/GSA-TTS/devtools-compliance
