### ISSUE TITLE
give feedback on new site review

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1330]
## Background Information

A New Site Review process is being stood up by the Digital Council.

cc https://github.com/18F/tts-tech-portfolio/issues/1109 https://github.com/18F/tts-tech-portfolio/issues/1205

## Implementation Steps

Give feedback on:

- [ ] [Guidelines](https://docs.google.com/document/d/1j6eieL3oop0rxCAldVVh7uGdOCG-ajafrog_BZ-u470/edit)
- [ ] [Questions](https://docs.google.com/document/d/1FYqfv_kb5OkDuKEmNVDv_DTsd3zfaFzCJgBGvnIpRoI/edit)
- [ ] [Go-Live Checker](https://docs.google.com/spreadsheets/d/19733OffGe01R68yPNP_k6gMeZc53urkqmBH2zMlYcMo/edit#gid=1232597517) - meant to be government-wide, rather than specific to TTS

## Acceptance Criteria

- [ ] Feedback provided
