### ISSUE TITLE
TTS Common Control Progress Monitoring Tool

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1344]
## Background
Heimdall2 is a persistent scan results viewer. With work being done to generate compliance artifacts the Heimdall results format provide the most viable and ready to use way track progress for https://github.com/18f/tts-common-controls

## Implementation Steps 

- [ ] Answer "who's the audience?"
- [ ] Answer "who's monitoring it?"
- [ ] Determine whether Security will accept the results for attestation

## Acceptance Criteria

- [ ] All controls with a planned implementation are being tracked and monitored

**Comment by JJediny** [comment]
Closing in favor of #1738
