### ISSUE TITLE
ATO for data.gov - due September 31 2021

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/tts-tech-operations#1448]
- **Main repository:** https://github.com/GSA/datagov-deploy
- **Site (will be; these currently point to the existing FCS environment):** 
  - https://catalog.data.gov (currently https://catalog-prod-datagov.app.cloud.gov)
  - https://inventory.data.gov (currently https://inventory-prod-datagov.app.cloud.gov)
  - https://labs.data.gov/dashboard (currently https://dashboard-prod-datagov.app.cloud.gov)
- **Product manager:** @mogul 
- **System Owner:** @hkdctol 
- **ISSO:** Lynnette Jackson
- **ISSM:** @rpalmer-gsa
- **ATO folder:** https://drive.google.com/drive/folders/0Bw0F8bl5XHDTUHVsNHFNZVIyU3c?resourcekey=0-5Xa_NI4DTKcAi17Lw_3YDA

## TODOs

If your system isn't live yet, "production" refers to the environment that _will_ be production.

#### Project team

- [x] Request ISSO
- [ ] Assign the appropriate labels to this issue.
- [x] Read the following:
  - [x] [Guidelines for GSA's Digital Presence](https://insite.gsa.gov/employee-resources/communications/digital-website-communication/policies-and-guidelines/guidelines-for-gsas-digital-presence)
  - [x] [Hello, production](https://blog.thepete.net/blog/2019/10/04/hello-production/)
  - [x] [The Engineering Practices Guide](https://engineering.18f.gov/), particularly:
    - [x] [Languages & Runtimes](https://engineering.18f.gov/language-selection/)
  - [x] [Before You Ship](https://before-you-ship.18f.gov), particularly:
    - [x] [Infrastructure](https://before-you-ship.18f.gov/infrastructure/)
    - [x] [Lifecycle of a Launch](https://before-you-ship.18f.gov/ato/)
  - [x] [The API Standards](https://github.com/GSA/api-standards), if you plan to have an API
- [x] Determine the [impact level](https://before-you-ship.18f.gov/ato/levels/) (FIPS-199 categorization).
  - [ ] Confirm with @afeld 
#### ISSO

- [x] Provide SSP template
- [x] Lay out long-term ATO path
- [x] Ensure that common technical controls are part of the architecture
  - [x] Code scanning
  - [x] [Dependency scanning](https://handbook.tts.gsa.gov/launching-software/security/#static-analysis)
  - [x] Input validation
  - [x] [Platform](https://before-you-ship.18f.gov/infrastructure/) selection

### Phase 1: Assessment prerequisites

Everything in this section needs to be completed before the project will be scheduled for an assessment.

#### Tech Portfolio Lead

- [ ] Set up an ATO intro meeting with the project team.
- [x] Set up the project ATO folder.

##### Technical

These tasks apply to every repository/application/hostname/language that is directly involved in your project.

- [x] Enable [protected branches](https://help.github.com/articles/about-protected-branches/) for the project repository.
  - Get help via #admins-github, if needed.
- [x] Ensure that your production environment is fully set up, and matches what's described in your ATO materials.
- [x] [Set up monitoring](https://before-you-ship.18f.gov/infrastructure/monitoring/)
  - [x] [Downtime alerts](https://before-you-ship.18f.gov/infrastructure/monitoring/#downtime)
  - [x] [Error & performance alerts](https://before-you-ship.18f.gov/infrastructure/monitoring/#errors--performance-problems)
  - [x] [DAP](https://digital.gov/dap/)
- [x] [Log required events](https://before-you-ship.18f.gov/infrastructure/logging/#what-to-log)
- [x] Perform security scans, and put the results (or a link to them) in the project's `ATO folder`.
  - [x] Set up [dependency analysis](https://before-you-ship.18f.gov/security/static-analysis/) service
    - [ ] Add service badge to your README
    - [ ] Put a point-in-time PDF of the scan results in the project's `ATO folder`.
  - [x] Set up [static code analysis](https://before-you-ship.18f.gov/security/static-analysis/)
    - [ ] If using a service, add the badge to your README.
  - [x] [Perform dynamic vulnerability scanning](https://before-you-ship.18f.gov/security/dynamic-scanning/)
    - [ ] Resolve any visible security issues, re-running the scan as needed
    - [ ] Add the issue-free scan report or documentation about false positives to the project's ATO folder.
- [x] If this is a new system, add a prominent [`Beta`](https://18f.gsa.gov/dashboard/stages/) label to the site.
- [x] Ensure the production environment has sufficient capacity to withstand the testing.
  - The testing tools create very heavy usage and traffic.
- [x] Architecture finalized

##### Documentation

...reading and writing.

- [x] Read the [Overview](https://before-you-ship.18f.gov/) and [the ATO section (including sub-pages)](https://before-you-ship.18f.gov/ato/) of Before You Ship.
- [x] Read the LATO guide.
  - Search [this page](https://insite.gsa.gov/topics/information-technology/security-and-privacy/it-security/it-security-procedural-guides) for "Lightweight Security Authorization Guide".
- [x] Read the [Checklist of Requirements for Federal Websites and Digital Services](https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/)
- [x] Read the [Guidelines for GSA's Digital Presence](https://insite.gsa.gov/employee-resources/communications/digital-website-communication/policies-and-guidelines/guidelines-for-gsas-digital-presence)
- [x] Request a [privacy threshold analysis (PTA)](https://before-you-ship.18f.gov/privacy/)
- [x] Complete a Privacy Impact Analysis (PIA) - determined if necessary by PTA
- [x] [Update relevant documentation](https://before-you-ship.18f.gov/ato/tips/), primarily the README.
- [x] [Fill out the System Security Plan (SSP).](https://before-you-ship.18f.gov/ato/ssp/)
  - [x] Sections 1-12
    - [x] [Architecture diagram](https://before-you-ship.18f.gov/ato/ssp/#diagrams)
  - [x] Section 13
- [x] Complete Digital Identity Acceptance (DIA)
- [x] Complete ISA documentation if required
- [x] Complete BIA
- [x] Complete Continuity of Operations (COOP) Plan
- [x] Complete Configuration Management Plan (CMP)
- [x] Complete Incident Response Plan
- [x] Complete Rules of Behavior for system
- [x] Remediate all control comments from ISSO

#### ISSO

- [x] Tailor documentation checklist above
- [x] Review Section 13

#### ISSO

1. [x] Submit sections 1-12 of SSP for Architecture Review
1. [x] Submit section 13 to ISSM for acceptance and movement forward for assessment if no issues remain
1. [x] Schedule a documentation review session.
   - One or more follow-up sessions may be necessary.

#### Program team

1. [x] Fix any documentation issues identified in the session.
1. [x] RoE signed
   - [x] System Owner
   - [x] GSA IT
1. [ ] Confirm you can access [Archer](https://before-you-ship.18f.gov/ato/archer/)

#### Project team

- [x] Environment (live system) finalized
- [x] Fully instantiate environment for assessment
  - Your SaaS/IaaS/PaaS should be generally configured for launch
- [x] Remediate High and Critical findings from scans
- [x] Fill out the Rules of Engagement (RoE)

#### ISSO+SecOps

- [x] Complete operating system (OS), database (DB), and/or container scanning
- [x] Complete Web Scanning for GSA implementation site (Netsparker)
- [x] Re-scan to ensure remediation

### Phase 4: Penetration testing

The following penetration tests will be performed:

- External Interfaces
- OWASPv4.1 & PTES-TG
- Gray Box
- Authenticated

#### Project team

- [x] Environment being tested is frozen (disable automated deploys to production)
- [x] Put all found vulnerabilities in the project's issue tracker
- [x] Fix any `Critical` or `High` vulnerabilities.
  - This needs to be done before the ATO can be issued, though not necessarily before the end of the assessment.

#### Testers

- [x] Deliver Penetration Test Report

#### ISSO

- [x] Request penetration test and assessment
- [x] Penetration test complete
- [x] Assessment scheduled

### Phase 5: Assessment

Needs to start within 30 days of penetration test.

#### Assessors

1. [x] Assessment kickoff meeting
1. [x] Complete [Security Assessment Plan (SAP)](https://insite.gsa.gov/employee-resources/information-technology/security-and-privacy/it-security/it-security-procedural-guides)

#### Project team

- [x] Polish up the System Security Plan (SSP).

### Phase 6: Post-assessment

1. [ ] Controls tested - Lynnette Jackson
1. [ ] Create a Plan of Actions and Milestones (POAM). - Lynnette Jackson
1. [ ] Final review and risk acceptance signatures (issue the ATO) - @afeld 
1. [x] Remove the `Beta` label from the site.
1. [ ] Fix all `Moderate` vulnerabilities - due [30 days after ATO issued]
1. [ ] Fix all `Low` vulnerabilities - due [60 days after ATO issued]
1. [x] [Join the TTS Private Bug Bounty](https://docs.google.com/forms/d/1lvCBb2-jc5nNi-5V8J3IZQ8TcvMj8BWwryo1Qk3e_Bc/edit) - due [60 days after ATO issued]
1. [x] Move to the TTS Public Bug Bounty - ask [#bug-bounty](https://app.slack.com/client/T025AQGAN/C0X2FMJ86) - due [two weeks after start] or two weeks after the last critcal/high report was triaged, whichever comes last
1. [ ] ATO letter signed
1. [ ] Cert letter signed
1. [ ] Launch

---

See the [Before You Ship](https://before-you-ship.18f.gov/ato/) site for more information.

/cc @18F/tts-tech-portfolio
