### ISSUE TITLE
create issues for all cross-TTS POAMs

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1505]
## Background Information

There are a number of problems that have been identified across a number of TTS system, whether they apply to all cloud.gov apps, all users of Route53, etc.

## Implementation Steps

- [ ] Audit for common POAMs
- [ ] Determine due dates
- [ ] Determine who has responsibility

## Acceptance Criteria

- [ ] Issues created for all known POAMs that affect multiple systems
- [ ] Decide how to get ahead of this in the future

**Comment by afeld** [comment]
Some I'm aware of:

- https://github.com/18F/tts-tech-portfolio-private/issues/1009
- https://github.com/18F/tts-tech-portfolio-private/issues/1010
