### ISSUE TITLE
TTS ATO for Github Enterprise

### ISSUE THREAD

**Issue by rpalmer-gsa** [GSA-TTS/tts-tech-operations#1532]
Create TTS Implementation of GitHub system. 

## Implementation steps

- [x] Upgrade [TTS GitHub organizations](https://handbook.tts.gsa.gov/tools/github/#organizations) to Enterprise Cloud
   - [ ] Confirm price
   - [ ] Confirm SaaS budget
   - [ ] Confirm schedule
   - [ ] Transfer funding
   - [ ] Upgraded
- [ ] Determine [compensating controls](https://docs.google.com/document/d/15xe_Xbxfc9HLma5nBr8xKjhilKmfph0fmqGiNFNyxQI/edit#heading=h.ahf4xmmshe4n)

## Acceptance criteria

- [ ] Use of TTS GitHub organizations is compliant for use in Moderate systems for the medium term

**Comment by afeld** [comment]
Likely following cloud.gov's lead here: https://github.com/cloud-gov/cg-compliance/issues/234

**Comment by afeld** [comment]
[The background](https://docs.google.com/document/d/15xe_Xbxfc9HLma5nBr8xKjhilKmfph0fmqGiNFNyxQI/edit#)
