### ISSUE TITLE
capture archer user stories for AO/Portfolio/SO

### ISSUE THREAD

**Issue by rpalmer-gsa** [GSA-TTS/tts-tech-operations#1538]
## Background Information

GSA IS is moving SSPs and POA&M into the Archer GRC tool. Both the TTS Technology Portfolio and System Owners will need access into the tool in order to view information. 

## Implementation Steps

- [x] Identify TTS user communities
- [ ] Identify TTS user stories and data
- [ ] Identify delta between capabilities and user stories

## Acceptance Criteria

- [ ] Provide TTS Tech Portfolio and System user stories and delta to Archer team for consideration.

**Comment by rocheller123** [comment]
Document to capture Archer user stories: https://docs.google.com/document/d/1LorlBYp0BBtnAA0UT5rLQaNoAZLxTGABSYo4PzsBbTA/edit#heading=h.no75ep1avew5

**Comment by afeld** [comment]
Left feedback in the doc. The main piece to focus on (and that I worry will be a step backwards) is the collaboration.

**Comment by MichaelSides** [comment]
- [ ] Review older "user stories"/information:  https://docs.google.com/document/d/1LorlBYp0BBtnAA0UT5rLQaNoAZLxTGABSYo4PzsBbTA/edit#heading=h.no75ep1avew5
- [ ] @MichaelSides and @Mgilesd to meet up on 5/23 to discuss way forward

**Comment by MichaelSides** [comment]
Closing, as OBE,  as Archer will be decommissioned and a new GRC tool implemented in FY25 by OCISO.
