### ISSUE TITLE
Cloud IaaS: Setup Prisma Cloud for all AWS accounts

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1544]
GSA's security team uses Prisma Cloud for checking IaaS/CSP account configuration and security posture.

Tech Portfolio would prefer to leverage this existing service for checking/auditing all of the AWS (and potentially GCP/Azure) accounts under administration.

## Implementation Steps
- [x] Request access to Prisma Cloud
- [ ] Ensure tech portfolio accounts have priv to onboard existing accounts

## Acceptance Criteria
- [ ] Determination made about the extent to which Tech Portfolio can use Prisma Cloud for its own CSP configuration monitoring needs
- [ ] TTS System owner access and scan sharing process is established.

**Comment by adborden** [comment]
@JJediny will groom.

**Comment by JJediny** [comment]
https://github.com/GSA/odp-tf-prisma-deps should be vendored into gsa-tts/aws-admin

**Comment by JJediny** [comment]
This issue cannot be worked until there is a TTS/GSA IT agreement over SoCaaS
