### ISSUE TITLE
Update TTS AWS root credential database to include MFA tokens for all accounts

### ISSUE THREAD

**Issue by adborden** [GSA-TTS/tts-tech-operations#1550]
## Background Information

In order to simplify management of MFA for AWS root users, Tech Portfolio wants the TOTP secret for virtual MFA devices stored encrypted in the TTS AWS root credential KeePassXC database. 

In our [AWS root user management guide](https://docs.google.com/document/d/14hNuAhOGy9j5SkkfLStA9sj9AA87Xd7gi7v6N1oDn4M/edit#heading=h.zbx5xfo4gxhu), we have a note that some accounts are missing the TOTP secret and instead the MFA exists only on a few individuals devices. We should update the entries so that all accounts in the database include the TOTP secret.

## Implementation Steps

- [ ] For each account missing the TOTP secret key in the KeePassXC database, log into the AWS account, replace the MFA device, and enter the secret key into the database
- [ ] Remove the note in the [AWS root user management guide](https://docs.google.com/document/d/14hNuAhOGy9j5SkkfLStA9sj9AA87Xd7gi7v6N1oDn4M/edit#heading=h.zbx5xfo4gxhu)

## Acceptance Criteria

- [ ] GIVEN I am attempting to login as the root user for a TTS AWS account
  WHEN I provide an MFA code and password from the KeePassXC database
  THEN I can successfully log in.

**Comment by afeld** [comment]
Took a pass and set up TOTP for the ones that I had in my authenticator. I don't have TOTP set up in my authenticator for any of the GovCloud ones. @JJediny Can you look at the remainder and see if there are any that you're unable to access and add?
