### ISSUE TITLE
M-21-31 CAP Phase 1:  Identify gaps in event logging requirements NLT 9/30/24

### ISSUE THREAD

**Issue by rocheller123** [GSA-TTS/tts-tech-operations#1555]
## Background Information

[M-21-31: Improving the Federal Government’s Investigative and Remediation Capabilities Related to Cybersecurity Incidents](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf) requires federal agencies to log information to aid in the "detection, investigation, and remediation of cyber threats" and to share information with other agencies, if required, to address cybersecurity risks or incidents. 

The required log information is broken down into 4 Event Logging (EL) tiers: EL0, EL1, EL2, EL3. 

The requirements for ensuring the information for each tier is being collected are as follows with specific deadlines from date of memo (8/27/2021):

- **Within 60 days of memo date**:  As per memo, "_Identify resourcing and implementation gaps associated with completing each of the requirements listed below. Agencies will provide their plans and estimates to their OMB Resource Management Office (RMO) and Office of the Federal Chief Information Officer (OFCIO) desk officer._"
-  **Within one year of memo date**: reach EL1 maturity as defined in [M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- **Within 18 months of memo date**: achieve EL2 maturity as defined in [M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf). 
- **Within 2 years of memo date**: achieve EL3 maturity as defined in [M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf). 

The first step is to identify the required information that is not being collected and to create a plan to ensure the information is being collected. 

## Implementation Steps

- [x] Identify groups that will be involved.
- [x] Identify tasks for groups.  
- [ ] Identify what log information is currently being collected. 
- [ ] Identify gaps in event logging requirements. 
- [ ] Develop a plan to address gaps. 

## Acceptance Criteria

- [ ] The gaps in the implementation of the logging requirements as per M-21-31 have been identified and an appropriate plan to complete implementation has been developed.

**Comment by afeld** [comment]
cc https://github.com/18F/aws-admin/issues/150

**Comment by rocheller123** [comment]
Discussed in Slack: https://gsa-tts.slack.com/archives/CG8SNAEQM/p1636040839007600

**Comment by MichaelSides** [comment]
Week of June 3rd:

- [ ] Repurposing NSF spreadsheet provided by Search.gov: [OMB M-21-31 status sanitized v01 20231002 working copy](https://docs.google.com/spreadsheets/d/1ikBLaYOxq8_Qeq4HbSFKaYn9nWAyZNoVdEZhZrTHFTI/edit#gid=554377163) 
- [ ] Discovery meetings with 
                  - [ ] Login
                  - [ ] Cloud
                  - [ ] USA
- [ ] Consolidate info provided and check on status of tracking spreadsheets
- [ ] Update

**Comment by MichaelSides** [comment]
Week of 7/8/24:

- [ ] Continue to assist with the SOCaaS TTS Decision Memo (as needed, due to M-21-31 dependencies):  https://github.com/GSA-TTS/tts-tech-operations/issues/1719
- [ ] Support reoccurring meetings with all impacted TTS systems
- [ ] Develop progress tracking metrics

**Comment by MichaelSides** [comment]
Week of 7/15/24:

- [ ] Re-engage with the major TTS Systems and outline the following Phase 1 plan:

1. Bi-weekly Meeting Cadence
2. Asking for spreadsheets to be completed/populated NLT week of Aug 12th
3. Q&A week of Aug 26th
4. Lenia and Mike to work on Phase 1 deliverable (discovery report) and present draft week of Sept 9th
5. Finalize Phase 1 deliverable Sept 23rd
6. Submit deliverable (discovery report) IAW the M-21-31 CAP NLT Sept 30th

- [ ] Meet with New Relic to establish a communications channel
- [ ] Investigate current logging status in New Relic
- [ ] Review information provided in the system tracking sheets and/or provided through a separate channel by the TTS Systems
- [ ] Review of the CAP TTS system list to ensure coverage in this discovery effort moving forward

**Comment by MichaelSides** [comment]
Week of 7/22/24:

- [ ]  Continue review information provided in the system tracking sheets and/or provided through a separate channel by the TTS Systems
- [ ] Schedule next bi-weekly sync meetings for week of 7/29/24
- [ ] Agree to a Phase 1 deliverable template
- [ ] Begin populating Phase 1 deliverable

**Comment by MichaelSides** [comment]
Week of 8/12/24:

- [ ] Continue to review and respond to information provided in the system tracking sheets and/or provided through a separate channel by the TTS Systems
- [ ]  Facilitate bi-weekly sync meetings 
- [ ]  Continue populating Phase 1 deliverable

**Comment by MichaelSides** [comment]
- [ ] By COB 8/20/24 LaKeisha has asked @MichaelSides & Lenia Cash for an updated Gantt Chart that aligns with the TTS CAP

**Comment by MichaelSides** [comment]
8/27/24:  @cash466 and @MichaelSides briefed TTS Senior Leadership during the Aug Program Review on progress and reiterated the challenge of collecting as much information and data as possible to facilitate a strong discovery report/Phase 1 Deliverable by Sept 30, 2024

https://docs.google.com/presentation/d/1NkS8ngBlB7GNtFc4lrQvjz2TsUjcU3rXh6DcBnJZRA8/edit#slide=id.g2f612db9ff2_0_142

**Comment by MichaelSides** [comment]
Week of 9/3/24:

- [ ] Continue to review and respond to information provided in the system tracking sheets and/or provided through a separate channel by the TTS Systems

- [ ] Facilitate bi-weekly sync meetings

- [ ] Continue populating Phase 1 deliverable (Discovery Report)

**Comment by MichaelSides** [comment]
Week of 9/9/24:

- [ ] Complete first draft of the Phase 1 deliverable (Discovery Report)

**Comment by MichaelSides** [comment]
Week of 9/16/24:

- [ ] Complete final draft of Phase 1 deliverable (Discovery Report)

**Comment by MichaelSides** [comment]
Stakeholders are finalizing comments on the final Phase 1 deliverable/draft https://docs.google.com/document/d/1BlFwsrCzKjk6uMGLgV6lRdoLRfS7ee5PGErxb9yCRmY/edit 

- [ ] Send out official report NLT COB 9/30/24
