### ISSUE TITLE
False positive console_login_without_mfa when logging in with GSA SecureAuth

### ISSUE THREAD

**Issue by adborden** [GSA-TTS/tts-tech-operations#1575]
## Background Information

As part of https://github.com/18F/aws-admin/issues/48, we found that when we logged in with SecureAuth, the console_login_without_mfa alarm is triggered.

## Implementation Steps

- [ ] If not configurable in Terraform, submit a PR upstream to grace module
- [ ] Disable console_login_without_mfa for the tts-jump account

## Acceptance Criteria

- [ ] WHEN I login to tts-jump with SecureAuth
  THEN Tech Portfolio does not receive a console_login_without_mfa alert
