### ISSUE TITLE
Convert Terraform to OpenToFU

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1665]
## Background Information

- [ ] Determine if https://github.com/18f/aws-admin can use [OpenToFU](https://opentofu.org/docs/cli/) 

## Implementation Steps

- [ ] Test current Terraform for compatibility
  - [ ] [aws-admin](https://github.com/gsa-tts/aws-admin)
  - [ ] [github issue templates](https;//github.com/gsa-tts/tts-tech-operations/)

## Acceptance Criteria

- [ ] Determine if Licensing requires a Transition.

**Comment by JJediny** [comment]
Closing until there is a need to reopen
