### ISSUE TITLE
FY24 - New Relic

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1671]
## Background Information

JP Flores will be the contracting officer (CO) and will reach out soon to schedule a project kickoff meeting. Please review the below information and the action items required to move forward. 

To help us reach a successful outcome, please be prepared to discuss the following topics at the project kickoff:

- Requirement overview, including IGCE
- Previous procurement history and market research
- Pertinent content in the drafted PWS, SOO, or SOW
- C-SCRM, IT approvals, security, IT accessibility and GFE/GFI if needed
- Timeline and schedule impacts, contingencies, risk level, and priority
- Desired acquisition strategy and evaluation criteria
- Project team roles & responsibilities (COR/PM/PO/CO/CS/Embedded PA)
- What does project success look like?

## Implementation Steps

- [ ] [Completed C-SCRM Criticality Analysis Tool (if applicable this requirement)](https://docs.google.com/spreadsheets/d/1s_L-fawgMHAoPTttPbriZ7-BOAX0fuX2FXSlDn-vx7k/copy) 

[Signed Not Inherently Gov Function Determination](https://docs.google.com/document/d/1f5lLgXg7-2xzZYCs2PfRYyZoWHuFeV28Ag5bo30dq2Q/edit)

- [ ]  [Signed COR Nomination Letter](https://docs.google.com/document/d/1BjJfeTeFHLIm0ek4X905M4uRcJRO1gDOelvFLV5sl2Q/edit?usp=sharing) & a [FAC-COR certification](https://docs.google.com/presentation/d/150DLS17QSMEqOmxQb6IedNr6vf2XACPq3-eBQK56MGg/edit#slide=id.g204d9d05435_1_0) documents @LaKeisha

- [ ]  Approved Purchase Request (Funding) or IAA: If this is an Assisted Acquisition (IAA), no further action is required. Use the below forms for all other internal funding requests:

  - [ASF PR Funds Request ](https://docs.google.com/forms/d/e/1FAIpQLSd8R2qFGMeK4WkRRob6yJy6H7Jx4bliqQIWVN4GzuiVptoz5Q/viewform)

  - [FCSF PR Funds Request ](https://docs.google.com/forms/d/1UWvkYZg1QInXAXRWbxeVjD99tE7dmINVkISumy97c2c/viewform?edit_requested=true)

  - [ARP PR Funds Request](https://docs.google.com/forms/d/e/1FAIpQLSdoEtcc0oGdI1ypl3zt3KMtKD58frXLOjy6CXZzM7oFPrRTpQ/viewform)
