### ISSUE TITLE
Github User Recertification (FY24) - Due 6/14

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1680]
[Final review and removal of Github Users identified as no longer active](https://docs.google.com/spreadsheets/d/1Xt0-QilCFrtagbIO4jf1VEucyP9BuOOpG0xcRw2Pcz8/edit#gid=968880020)

Identified needing further review to determine GSA active status:

Review other legacy orgs @JJediny 
- [x] https://github.com/presidential-innovation-fellows
- [x] https://github.com/project-open-data
- [x] https://github.com/FedRAMP
- [x] https://github.com/digitalgov
- [x] https://github.com/fellows-in-innovation
- [x] https://github.com/digital-analytics-program

Create new tab for each org, import/export/timestamp and add task list

Done to support:
- Github FY24 License Count and 18F transfer under GSA enterprise buy
- GSA Pages User Audit and Google Group memberships per website
- GSA FY24 Annual User Recertification 

## Acceptance Criteria
- We have an accurate user count
  - We have a user count that accounts for the user in multiple orgs
- We have a license count for all TTS users and projected new hires for FY25

@MichaelSides 
```[tasklist]
### Tasks
- [x] GSA
- [x] USA.gov
- [x] 18F
- [x] GSA-TTS
- [x] USWDS
- [x] PIF
- [x] DigitalAnalyticsProgram
- [x] FEDRAMP
- [x] ProjectOpenData
```

**Comment by JJediny** [comment]
- [ ] @JJediny email Data.gov about ProjectOpenData membership 6/11

**Comment by JJediny** [comment]
Complete 6/20

- [x] Provided COR with 1200 license requestted
- [x] Funding POCs and EASi Budget Line provided
