### ISSUE TITLE
Create allstar outside contributor exemption

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1684]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA/digitalgov-pra/issues/367
- [x] Create update branch
- [x] Push updates to update branch
- [x] Creaete Pull Request for peer view/review/feedback
- [x] Merge to main branch
- [x] Review/Feedback
- [x] Acceptance - Peer review and merged into main.
- [x] Close issue
```

**Comment by nateprice18f** [comment]
Created allstar outside contributor exemption, branch merged into main.
