### ISSUE TITLE
Cloud IaaS: Address AWS-Admin TF CKV issues.

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1686]
```[tasklist]
### Tasks
- [ ] CKV_AWS_144: "Ensure that S3 bucket has cross-region replication enabled" (Bootstrap)
- [ ] CKV2_AWS_67: "Ensure AWS S3 bucket encrypted with Customer Managed Key (CMK) has regular rotation" (Bootstrap)
- [ ] CKV_AWS_145: "Ensure that S3 buckets are encrypted with KMS by default" (Bootstrap)
- [ ] CKV2_AWS_61: "Ensure that an S3 bucket has a lifecycle configuration" (Bootstrap)
- [ ] CKV2_AWS_6: "Ensure that S3 bucket has a Public Access block" (Bootstrap)
- [ ] CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK" (Bootstrap)
- [ ] CKV_TF_1: "Ensure Terraform module sources use a commit hash" (Module TF)
```

**Comment by JJediny** [comment]
Will be decommisioning AWS-ADMIN in favor of FCS terraform modules
