### ISSUE TITLE
Ops Rotation -- Nate and Mike Week of June 3rd 2024

### ISSUE THREAD

**Issue by MichaelSides** [GSA-TTS/tts-tech-operations#1694]
**Updated with the new template:**
---
name: Operations Rotation
about: Tasks to be completed during each Operations Rotation
title: OpsRotation <start>-<end>
labels: "g: accepted, i: misc"
assignees: ""
---

Each of the following should be done within the dates above.

## Perform actions in accordance with

- [Standard Operating Procedures](https://docs.google.com/document/d/1Quv2TL5cOywqedS7iVWMWp3SMRXVy0sysOlWhO8MUFU/edit)
- [Playbook](https://github.com/GSA-TTS/tts-tech-operations/blob/main/how_we_work/ops_rotation.md)

## GitHub

- [x] [Add issues from linked repositories to our project boards](https://github.com/orgs/GSA-TTS/projects/51/views/1?)
  - [x] [Issues](https://github.com/orgs/GSA-TTS/projects/51/views/1?)
  - [x] [Pull requests](https://github.com/orgs/GSA-TTS/projects/51/views/1?)
- [x] Review and ideally merge (or close) open [pull requests to Tech Operations repositories](https://github.com/GSA-TTS/tts-tech-operations/blob/main/README.md)
  - If you need help reviewing/merging any, ask in [#tts-tech-operations-private](https://gsa.enterprise.slack.com/archives/GP559GCLD) or another relevant channel.
- [x] [Review Github Repos maintained by Tech Operations](https://github.com/GSA-TTS/tts-tech-operations/blob/main/README.md)

- Perform actions in accordance with:
  - [Github Standard Operating Procedures](https://docs.google.com/document/d/1Quv2TL5cOywqedS7iVWMWp3SMRXVy0sysOlWhO8MUFU/edit#heading=h.1kxielcf3jh3)
  - [GSA Github Administration](https://github.com/GSA/GitHub-Administration)

## Communications Monitoring

Ensure you are present in the following and are responding as needed:

- [x] [Slack Channels](https://github.com/GSA-TTS/tts-tech-operations/blob/main/how_we_work/ops_rotation.md#slack-channels)
- [x] [Google Groups](https://github.com/GSA-TTS/tts-tech-operations/blob/main/how_we_work/ops_rotation.md#google-groups) - Ensure all inbox items are marked completed. If not able to complete, use the `assign` task function to task the next person on ops rotation, providing them with a description of what's left to do to complete.
- [x] [New Relic](https://gsa.enterprise.slack.com/archives/C14EF2XEC) - `TEMP` assign @jjediny to all requests until further notice
## Other

- [ ] Perform any outstanding `ACCOUNT DEACTIVATION (TP)` (Task(s) Due) [offboarding tasks](https://docs.google.com/spreadsheets/d/1YWVryXSFp52cvus6Sml3lK1Mmaz1pO4RYZKCPRQMfqs/edit). For any individual where Tasks are due, find their sheet (ordered by offboarding date) and look at the "ACCOUNT DEACTIVATION (TECH PORTFOLIO)" section for any tasks that should be completed.
- [x] Check the [anonymous feedback responses](https://docs.google.com/spreadsheets/d/1ahj7CuoTAYr5c7miDCeGhplYx_wW1yj6ApMFLRdY-7Q/edit?usp=forms_web_b#gid=1730986218), and do the following as applicable:

## Closeout
- [x] Slack Requests - have a :done-check: emoji when completed
- [x] Google Groups - next person performing ops using are assigned using Google Tasks if issue still being worked.
- [ ] Setup a quick meeting if needed with next person performing ops-rotation if needed 
```[tasklist]
### Tasks
- [x] Monday - Nate
- [x] Tuesday - Mike
- [x] Wednesday - Mike
- [x] Thursday - Mike
- [x] Friday - Nate
- [ ] https://github.com/GSA-TTS/tts-tech-operations/issues/1701
```

**Comment by MichaelSides** [comment]
New Relic:  Matt and John have the two admin licenses.  Possibly have Matt transfer a license for rotation moving forward.  For now, delegate any new requests to John.  

SecureAuth currently used.  SCIM.

**Comment by MichaelSides** [comment]
FYI:  I did not scrub the Offboarding spreadsheet, but did remove [scott.reuber@gsa.gov](mailto:scott.reuber@gsa.gov) from both the TTS github and mural orgs by slack requests.
