### ISSUE TITLE
Address GSA/.allstar scan failure

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1697]
```[tasklist]
### Tasks
- [x] Follow up GSA/allstar run failure.
- [x] Error: Process completed with exit code 137. - Low memory
- [x] Prior failures runs are after (need to review more) : {"severity":"INFO","org":"GSA","repo":"InterimPerformance-Dot-Gov-2018","area":"Binary Artifacts","enabled":true,"time":"2024-05-31T14:30:16Z","message":"Check repo enabled"}
```

**Comment by nateprice18f** [comment]
Future version of Allstar release to address failure. 
https://github.com/ossf/allstar/issues/511

**Comment by nateprice18f** [comment]
[#41](https://github.com/GSA-TTS/.allstar/issues/41)

**Comment by JJediny** [comment]
Resolved github actions failure 9/26
