### ISSUE TITLE
Nate COR Training

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1698]
```[tasklist]
### Tasks
- [x] FCR 110 Contracting Officer’s Representative (COR) Level I (8 CLPs)
- [x] FAC 079 Past Performance (1.5 CLPs)
- [x] FCL-CM-2500 Category Management 101 (1 CLP)
- [x] FAC 038 Integrating Sustainable Acquisition (2 CLPs)
- [x] FAC 043 Ethics & Procurement Integrity for the Acquisition Workforce (1 CLP)
- [x] CLM 031 Improved Statement of Work (3 CLPs)
- [x] CON 0130 (previously CLC 013) Services Acquisition (2 CLPs)*
- [x] CLE 028 Market Research (3 CLPs)
```
