### ISSUE TITLE
Review Github Issue Templates

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1700]
Review Current Templates:
- [ ] https://github.com/GSA-TTS/tts-tech-operations/tree/main/.github/ISSUE_TEMPLATE
- [ ] https://github.com/GSA-TTS/gsa-pages/tree/main/.github/ISSUE_TEMPLATE

```[tasklist]
### Tasks
- [ ] General Issue Template
```
