### ISSUE TITLE
Onboarding Email Automations

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1729]
```[tasklist]
### Tasks
- [x] Create/update formula to pull data from primary sheet
- [x] Create formula evaluate which email template to use
- [x] Weekly meeting with Ethan and onboarding team.
- [x] Find out how people work.... Terllo,Github,other
```

```[tasklist]
### Tasks
- [x] Create formula for 7 days
- [x] Create formula for 21 days hiring manager
- [x] Create formula for 14 days -
- [x] Create formula for 21 days - on boarding
- [x] Update formula for sending email to onboarding team for missing sup
```

```[tasklist]
### Tasks
- [x] Demo email notification functions
- [x] Update formulas
- [x] address ongoing user feedback
```

**Comment by nateprice18f** [comment]
Check IF hiring manger first then check IF onboarding buddy is there.

**Comment by nateprice18f** [comment]
={FILTER({Onboarding_Tracker!A:A,Onboarding_Tracker!B:B,Onboarding_Tracker!AK:AK,Onboarding_Tracker!F:F,Onboarding_Tracker!C:C,Onboarding_Tracker!AM:AM,Onboarding_Tracker!AX:AX,Onboarding_Tracker!BA:BA,Onboarding_Tracker!BC:BC,Onboarding_Tracker!BD:BD,Onboarding_Tracker!AE:AE,Onboarding_Tracker!AR:AR,Onboarding_Tracker!BW:BW},Onboarding_Tracker!F:F - TODAY() <= 21,Onboarding_Tracker!F:F > TODAY(),Onboarding_Tracker!BV:BV = "",Onboarding_Tracker!C:C = "External hire",Onboarding_Tracker!D:D = "Onboarding");

FILTER({Onboarding_Tracker!A:A,LEFT(Onboarding_Tracker!B:B,5),Onboarding_Tracker!AK:AK,Onboarding_Tracker!F:F,Onboarding_Tracker!C:C,Onboarding_Tracker!AM:AM,Onboarding_Tracker!AX:AX,Onboarding_Tracker!BA:BA,Onboarding_Tracker!BC:BC,Onboarding_Tracker!BD:BD,Onboarding_Tracker!AE:AE,Onboarding_Tracker!AR:AR,Onboarding_Tracker!BW:BW},Onboarding_Tracker!F:F - TODAY() <= 21,Onboarding_Tracker!F:F > TODAY(),Onboarding_Tracker!BV:BV = "",Onboarding_Tracker!C:C = "External hire",Onboarding_Tracker!D:D = "Onboarding")}

**Comment by nateprice18f** [comment]
=If(OR(K2 = "", L2 = ""), 'Email templates'!$A$16, "")
=If(OR(I2 = "", J2 = ""), 'Email templates'!$A$15, "")
=QUERY(SPLIT(QUERY(SPLIT(K2,",",TRUE,TRUE),"Select Col2")," ",TRUE,TRUE),"Select Col1")
