### ISSUE TITLE
GSA Auth  - Optimal Workshop

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1739]
```[tasklist]
### Tasks
- [x] Submit Intake Form https://docs.google.com/forms/d/e/1FAIpQLSeyPMkNiJh70lPl2xsbg1UUeg5D-QG22YpoSVJlQQnpHeCeMw/viewform
- [x] Pull User Report for notification
- [x] Pre-communications to Users
- [x] Swap SecureAuth to Okta SAML Certificate
- [x] Date selected to swap out IDP
```

**Comment by JJediny** [comment]
8/23 Provided the updated metadata file for the vendor to replace, awaiting confirmation
