### ISSUE TITLE
TTS Contract Training - Jediny

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1742]
```[tasklist]
### Tasks
- [x] FCL-CM-2500 Category Management 101
- [x] FCL-GSA-OGP0030 Performance-based Acquisitions
- [x] FAC 097 Navigating Buy American and Trade Agreements
- [ ] FCL-GSA-M889C GSA Section 889 course
```
[FCL-CM-2500 Category Management 101](https://dau.csod.com/ui/lms-learning-details/app/curriculum/f7144f64-7b36-4c54-9835-2e0926a5f017)
[FCL-GSA-M889C GSA Section 889 course](https://dau.csod.com/ui/lms-learning-details/app/curriculum/bf8cc73c-14f2-4e50-8cd8-acec3c3cb04d)
[FAC 097 Navigating Buy American and Trade Agreements This course replaced FAC 063. Previous completion of FAC 063 satisfies mandatory training requirements.](https://dau.csod.com/ui/lms-learning-details/app/curriculum/0c1c3482-e4a4-4a4a-88f6-d89a66b6254f)
[FCL-GSA-OGP0030 Performance-based Acquisitions Mandatory for the following: All CORs with an active delegation on acquisitions coded as “performance based” All COs with an acquisition warrant.](https://dau.csod.com/ui/lms-learning-details/app/curriculum/c0c4968d-2577-4630-94bc-67f3f4a2a481)
