### ISSUE TITLE
GSA Auth - Figma

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1745]
```[tasklist]
### Tasks
- [x] Submit Intake Form https://docs.google.com/forms/d/e/1FAIpQLSeyPMkNiJh70lPl2xsbg1UUeg5D-QG22YpoSVJlQQnpHeCeMw/viewform
- [x] Pre-communications to Users
- [x] Setup new SAML
- [x] Date selected to swap out IDP (10/11/24)
- [x] Swap SecureAuth to Okta SAML Certificate
```

**Comment by JJediny** [comment]
https://www.figma.com/files/1233938721735543664/admin/members?fuid=1334280196415662476

CSV user list pulled

**Comment by JJediny** [comment]
8/27 GSA Auth POC janaki.bhogineni@gsa.gov meeting and follow up 

```
<html>
<body>
<!--StartFragment--><div class="aju" style="cursor: pointer; align-items: center; display: flex; float: none; height: 80px; padding: 0px 16px; min-width: 40px; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aCi" style="position: relative;"><img id=":mx_423-e" name=":mx" src="https://lh3.googleusercontent.com/cm/AGPWSu_AXE4nmFy4SlQzkufyKRk5N7c6qkq6XQUnPavJ8z0fgOO21ZHSJMdn2dzqiVHisxA7Iw=s40-p" class="ajn" jid="janaki.bhogineni@gsa.gov" data-hovercard-id="janaki.bhogineni@gsa.gov" data-name="Janaki Bhogineni - IDT-C" aria-hidden="true" style="width: 40px; height: 40px; border-radius: 50%; display: block; background-color: rgb(204, 204, 204);"></div></div><div class="gs" style="margin: 0px; min-width: 0px; padding: 0px 0px 20px; width: initial; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gE iv gt" style="font-size: 0.875rem; cursor: pointer; padding: 20px 0px 0px;">
Janaki Bhogineni - IDT-C | Janaki Bhogineni - IDT-C | Mon, Aug 26, 6:05 PM (2 days ago) |   |  
-- | -- | -- | -- | --
Janaki Bhogineni - IDT-C
to me | to me
to me

</div><div id=":j6w"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="wl4W9b" jsaction="LNSvUb:.CLIENT;xSdBYb:.CLIENT;CDWmBe:.CLIENT;EtHLdc:.CLIENT;pQnh7:.CLIENT;pKHw7e:.CLIENT;Z03mxd:.CLIENT;NZLNxf:.CLIENT;bXglpe:.CLIENT;mzh2Bc:.CLIENT" style="display: flex;"></div></div><div class=""><div class="aHl" style="margin-left: -38px;"></div><div id=":jrn" tabindex="-1"></div><div id=":jrx" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTgwODQ4OTQzMDQ5MzU4NDU3MyJd; 4:WyIjbXNnLWY6MTgwODQ4OTQzMDQ5MzU4NDU3MyIsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDBd" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem; overflow-x: hidden;"><div id=":j7d" class="a3s aiL " style="direction: initial; font: small / 1.5 Arial, Helvetica, sans-serif; overflow: auto hidden; position: relative;"><div dir="ltr">Hi John,<div><br></div><div>As discussed, I am sharing the Prod app "Figma-GSA" metadata with you. Please check with the vendor regarding downtime needed or any possibility of eliminating downtime. You can also plan any access management or authorization requirements with the vendor regarding new integration with GSA Auth(OKTA)<br><br>Please find the metadata of IDP here for "Figma-GSA" integration.<br><a href="https://auth.gsa.gov/app/exkbpdelllf4eqRHT4h7/sso/saml/metadata" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://auth.gsa.gov/app/exkbpdelllf4eqRHT4h7/sso/saml/metadata&amp;source=gmail&amp;ust=1724856404943000&amp;usg=AOvVaw1qywLRMWgSG4Q0Zi6y8-Vm" style="color: rgb(17, 85, 204);">https://auth.gsa.gov/app/<wbr>exkbpdelllf4eqRHT4h7/sso/saml/<wbr>metadata</a></div></div></div></div></div></div><!--EndFragment-->
</body>
</html>
```

**Comment by cash466** [comment]
10/2/24 sent pre communication to user - planned authentication change for Friday 10/11/24

**Comment by JJediny** [comment]
We confirmed access with 5 users and turned on SSO only, let me know if you need anything else to close we will have to carry a POAM for encryption (until/if it becomes supported by the vendor)
