### ISSUE TITLE
AWS Training & Research 

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1746]
```[tasklist]
### Tasks
- [x] https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-bedrock-achieves-fedramp-high-authorization/
- [x] AWS Certified AI Practitioner training (https://aws.amazon.com/certification/certified-ai-practitioner/?ch=sec&sec=rmg&d=1)
```

```[tasklist]
### Tasks
- [x] AWS Certified Cloud/AI Practitioner Certification Exam Prep (https://aws.amazon.com/certification/certified-ai-practitioner/?ch=sec&sec=rmg&d=1)(https://aws.amazon.com/certification/certified-cloud-practitioner/?ch=sec&sec=rmg&d=1)
```
