### ISSUE TITLE
Problem Statements Workshop

### ISSUE THREAD

**Issue by nateprice18f** [GSA-TTS/tts-tech-operations#1749]
```[tasklist]
### Tasks
- [ ] Top 3 Problem Statements
- [ ] Problem Statement Format
- [ ] What is our story....
```
