### ISSUE TITLE
GSA Auth - AWS Jump Account

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1752]
Tech Operations created a secureauth jump implementation for Data.gov to login with MFA into their AWS Accounts. Users are on/offboarded through [Pull Requests to aws-admin](https://github.com/GSA-TTS/aws-admin/pulls?q=is%3Apr+is%3Aclosed). 

https://github.com/GSA-TTS/aws-admin?tab=readme-ov-file#usage

Review needed to determine if new AWS Id Center is a replacement for our custom implementation
- [x] Alternative Review
  - [x] [IAM Identity Center](https://us-east-1.console.aws.amazon.com/singlesignon/home?region=us-east-1#/instances/722318edfac2fef2/dashboard)
  - [ ] [AWS Admin Jump Setup](https://github.com/gsa-tts/aws-admin) 
 
```[tasklist]
### Tasks
- [x] Submit Intake Form https://docs.google.com/forms/d/e/1FAIpQLSeyPMkNiJh70lPl2xsbg1UUeg5D-QG22YpoSVJlQQnpHeCeMw/viewform
- [x] Swap SecureAuth to Okta SAML Certificate
- [x] Pre-communications to Users
- [x] Date selected to swap out IDP
- [x] Setup swap verification meetiing with Data.gov
```

**Comment by JJediny** [comment]
Kickoff Meeting scheduled 9/9/24 need to submit intake

**Comment by JJediny** [comment]
9/11

Determined we will swap IDP providers for secureauth for GSA Auth in `tts-jump` we will need to notify the Data.gov team about the switch

and separately follow up with GSA Auth team to setup IDP for Payer IAM Identity Center to manage sandbox access and natively support cloudtrail events and cloudwatch for non-SAML based authentication. Ideally we would roll out this with all programs and their teams for AWS access.

**Comment by JJediny** [comment]
Confirmed with tyler.burton@gsa.gov that the Data.gov team is aware of the pending swap and we will align with their team timing and testing

**Comment by JJediny** [comment]
GSA Auth team invited me to their enterprise meeting with Okta to discuss alternatives 11/12/24

**Comment by JJediny** [comment]
Communications sent out decommissioning planned for 11/29/24 closing
