### ISSUE TITLE
GSA Auth - AWS Jump

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1754]
We currently host the jump account for the Data.gov program using https://github.com/gsa-tts/aws-admin which uses terraform to implement assume-roles based on the SecureAuth mapping of `EmailAddress` to match the permissions they have access to.

AWS has a new service that may be a better replacement over refactoring https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html

```[tasklist]
### Tasks
- [x] Submit Intake Form https://docs.google.com/forms/d/e/1FAIpQLSeyPMkNiJh70lPl2xsbg1UUeg5D-QG22YpoSVJlQQnpHeCeMw/viewform
- [ ] Swap SecureAuth to Okta SAML Certificate
- [ ] Pre-communications to Users
- [ ] Setup new SAML
- [ ] Date selected to swap out IDP
```

**Comment by JJediny** [comment]
Closing duplicate of #1752
