### ISSUE TITLE
GSA Auth - Yello

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1756]
```[tasklist]
### Tasks
- [x] Submit Intake Form https://docs.google.com/forms/d/e/1FAIpQLSeyPMkNiJh70lPl2xsbg1UUeg5D-QG22YpoSVJlQQnpHeCeMw/viewform
- [x] Swap SecureAuth to Okta SAML Certificate
- [x] Pre-communications to Users
- [x] Date selected to swap out IDP
```

**Comment by MichaelSides** [comment]
Kickoff meeting scheduled with GSA Auth/SSO team on Weds 9/4/24

**Comment by MichaelSides** [comment]
Reviewed vendor/SP documentation and filled out and submitted the onboarding form:  https://www.google.com/url?q=https://docs.google.com/forms/d/e/1FAIpQLSeyPMkNiJh70lPl2xsbg1UUeg5D-QG22YpoSVJlQQnpHeCeMw/viewform?usp%3Dpp_url%26entry.1575062603%3DYello%26entry.1068241573%3DSecureAuth598%2B(DEV%2BMFA)%26entry.483303120%3DMichael%2BSides,%2BLenia%2BCash%26entry.575285402%3Dmichael.sides@gsa.gov,%2Blenia.cash@gsa.gov%26entry.2110339142%3DSAML%26entry.1387294741%3DTBD%26entry.1062551902%3DTBD%26entry.924159126%3DEmailAddress%26entry.562747773%3DEmail%2BAddress%26entry.1930524982%3DSHA256%26entry.450740736%3DSHA256%26entry.971241504%3DNone%26entry.307660433%3DNone&sa=D&source=calendar&ust=1725885715702981&usg=AOvVaw0zgxUmdJsI0ihj-NTAmk64

**POTENTIAL BLOCKER:**  Sent a request to the vendor/SP for assistance in definitively identifying the Assertion Consumer Services (ACS) URL(s) and Audience URI (SP Entity ID).  There is limited information in the FedRAMP SSP and terminology is not matching up.

**Comment by MichaelSides** [comment]
9/5/24:  The vendor/SP provided metadata file for prod environment, which was added to the intake form.  Project has officially kicked off.

**Comment by MichaelSides** [comment]
Week of 9/30/24:  System Owner has given green light to migrate to GSA Auth in PROD.

- [ ] Attend cutover meetings
- [ ] Facilitate migration and testing
- [ ] Close Out

**Comment by MichaelSides** [comment]
10/8/24:  Testing is underway with the System Owner, unsuccessfully.  Redirects back to the original login screen.  Vendor troubleshooting.

**Comment by MichaelSides** [comment]
10/15/24:  GSA Auth/PIV login testing is now successful.  Waiting on System Owner to close out the migration.
