### ISSUE TITLE
better password management

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#178]
Follow-up to #30. KeePassXC + Drive File Stream works, but isn't ideal. Similarly, getting more and more services under single sign-on is great, but there will always be a limit.

## User stories

- As the Tech Portfolio, I want members of TTS to use strong, distinct passwords.
- As a member of TTS, I don't want to have to remember my passwords.
- As a member of a group with shared passwords (Twitter, AWS root, etc.), I want an easy way to share them.

## TODO

- [ ] Explore the market for password management SaaS
- [ ] Determine if other parts of government are using anything for this
- [ ] Determine if any could be purchased under the micropurchase threshold
- [ ] If not, put out a solicitation

**Comment by afeld** [comment]
Closing as stale.

**Comment by its-a-lisa** [comment]
Opening based on question coming up from cloud.gov 
cc: @pburkholder

**Comment by pburkholder** [comment]
This may be moot. We thought we may need a means for leadership of cloud.gov to stash password in Drive.

If we do need to do this, we'd heard before that Drive unshared Google Sheets were OK for storing passwords. **Is this still true?**

But we're instead trying to document how/who can do account recovery through other means, like control of email and having a credit card (or equivalent). We'll see.

**Comment by its-a-lisa** [comment]
These are [TTS current requirements for passwords](https://handbook.tts.gsa.gov/password-requirements/)

**Comment by JJediny** [comment]
Closing in favor of https://github.com/GSA-TTS/tts-tech-operations/issues/1691
