### ISSUE TITLE
Github User Audit and Onboarding Update- Update to Github User Tracker

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1784]
Closes #1770 

## Follow up / Action Items

All TTS Github Orgs have been transferred into GSA Github Enterprise. We have been asked to recertify GSA IT preference to track and document all new requests to [Github User Tracker](https://docs.google.com/spreadsheets/d/1Xt0-QilCFrtagbIO4jf1VEucyP9BuOOpG0xcRw2Pcz8/edit?gid=317716196#gid=317716196)

- [ ] #1828
  - [ ] Date Requested
  - [ ] GSA Email
  - [ ] Github User associated with GSA Email
 
```[tasklist]
### Tasks
- [x] https://github.com/presidential-innovation-fellows/
- [x] https://github.com/usagov
- [x] https://github.com/18F
- [x] https://github.com/digital-analytics-program
- [x] https://github.com/FedRAMP
- [x] https://github.com/digitalgov
- [x] https://github.com/uswds
```

**Comment by JJediny** [comment]
User exports folder - https://drive.google.com/drive/u/0/folders/10j5lcKb4vP8qjnC-QROfzposanB23voe
 which is needed to update the tracking sheet - https://docs.google.com/spreadsheets/d/1Xt0-QilCFrtagbIO4jf1VEucyP9BuOOpG0xcRw2Pcz8/edit?gid=968880020#gid=968880020

**Comment by JJediny** [comment]
https://docs.google.com/spreadsheets/d/1y6vfV4z-jyqdLGnzUXvpJMNF48RCdWpo8LbUkkfJM7M/edit
