### ISSUE TITLE
Docker User Audit - Email Bounce Backs

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1789]
Email for GSA Auth Enrollment identified the following users with email bounce backs

```[tasklist]
### Tasks
- [x] matthew.bogdan@gsa.gov
- [x] joseph.raetano@gsa.gov
- [x] joseph.raetano@gsa.gov
- [x] sean.starnes@gsa.gov
- [x] elie.berkowitz@gsa.gov
- [x] b.ryan.johnson@gsa.gov
- [x] edward.narkiewicz@gsa.gov
- [x] melissa.miller@gsa.gov
- [x] james.moy@gsa.gov
- [x] jonathan.hart@gsa.gov
- [x] phillip.walsh@gsa.gov
```

**Comment by JJediny** [comment]
Users removed
