### ISSUE TITLE
Figma - User Management Documentation

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1805]
```[tasklist]
### Tasks
- [x] Determine who will Admin user requests 18F Design/Login/Tech Operations?
- [ ] Document Current Admins and how delegated user management
- [x] Update SOP/Servicenow for Opsrotation/SaaS
```
