### ISSUE TITLE
SaaS User Reports

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1806]
## Implementation Steps

- [ ] Document steps to produce a CSV/TSV export from all our SaaS products to double check license counts

## Acceptance Criteria

[Airtable MVP User Management Dashboard](https://airtable.com/appa1GhxDqGDhhen8/tblTwaqNlsxq2nQ3J/viwJSGjJySzHQBoB4?)

- [ ] New Relic

https://one.newrelic.com/admin-portal/organizations/users-list?state=a7944da2-cb2b-f61e-ad2d-796ecff3f423
![image](https://github.com/user-attachments/assets/eb3b8722-1df0-4804-91dd-0a6fbd957bc3)

**Comment by JJediny** [comment]
### Update 12/10

Successfully documented a re-import airtable base, ran into an issue automating the Lookup to automatically populate matching emails. Submitted a support ticket here is the response. If this does not work will migrate to Google Sheets and use standard VLOOKUP

```
Hi John,
 
Guillermo from Airtable Support, thanks for reaching out.
Happy to advise on how to set up your base to recreate the functionality of a VLOOKUP. An important distinction is that in Airtable you will manually select ("link") records (rows) from one table to records in another rather than finding matches programmatically (at least in part) You'll need:

A [linked record field](https://support.airtable.com/docs/how-to-link-records-in-airtable) to specify a relationship between records across two tables (If the manual linking feels like a lot of work/doesn't make sense for your workflow, there's a good chance that you should consider [combining tables](https://support.airtable.com/docs/combining-multiple-tables-into-one-table-using-views))

A [lookup or rollup field](https://support.airtable.com/docs/formulas-vs-other-computed-fields) — this pulls in the field value (or aggregate) of your choice from the linked table

A [conditional rollup](https://support.airtable.com/docs/conditional-counts-lookups-and-rollups) — here, instead of pulling in all linked values, you'll pull in only values that match a certain criteria, which you can define in an [IF statement](https://support.airtable.com/docs/how-to-write-nested-if-statements). This captures the functionality in the VLOOKUP which actually does the matching.

For a more in-depth overview of the VLOOKUP equivalent in Airtable, please check out our Table Talk clip on the topic [here](https://airtable.wistia.com/medias/rklzlh8e5f).

Also, the automatic method, some customers have used [this script from the community](https://community.airtable.com/t/vlookup-for-airtable/6903/5?u=dannym) to achieve VLOOKUP-like functionality. This script can be slow on large tables for two reasons:
a) it performs a nested for-loop in which all records in the lookup table is iterated for every record in the main table

b) it does updateRecordAsync calls one-by-one for each record

I hope this will guide you in the right direction.
```

**Comment by JJediny** [comment]
New approach. We are going to run a repeatable export to Google Sheets now using Appsheet as a relational database to MVP linking user lookup to software products used

**Comment by JJediny** [comment]
From @ethanheppner 

I ended up working on the [Software User Databse AppSheet](https://www.appsheet.com/template/AppDef?appName=TTSSoftwareUserDatabase-119646023&appId=ccd1e2a1-236e-4052-a387-da993c48bd6d&quickStart=False&nonce=0.38210522848467043#Data.Columns.Figma) 

...still have some to-dos (feel free to experiment while I'm out):
- [ ] How can we make the desktop version look as clean as the mobile one?
- [ ] How can we make a better interface for comparing offices' current software usage against their limits?
- [ ] How can we build default views for users that will only be interested in their teams' usage?
Let me know if you can figure any of these problems out and will look forward to checking in again on Tuesday.
