### ISSUE TITLE
New Relic - User Re-certification & Data usage review

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1807]
## Background Information

New Relic is a legacy product that has been used while many changes have been made to the cost model effecting Group/User/Services.

Review needed to ensure accounts are properly named, budget/funding is aligned with Full vs Basic Users and Data Usage. 

## Implementation Steps

[IGCE](https://docs.google.com/spreadsheets/d/1A9EQGtA9KH7XDp9yEPVVkFszT-hZOX1w5kjxMuRl2Z0/edit?gid=0#gid=0)

```[tasklist]
### Tasks
- [x] @mtaylor-gsa review issue for completeness
- [x] Pull Full User list and ensure active directory status
- [x] Rename "Group #" to program name matching budget
- [ ] https://github.com/GSA-TTS/tts-tech-operations/issues/1830
- [ ] Ensure Full Platform licenses are fully allocated
- [ ] Submit FY25 User Recertification to ISSO
- [ ] Revitalize New Relic Community of Practice to most efficiently utilize the Service
- [ ] Documentation on how to provide best value to Basic Users
```

## Acceptance Criteria

- [ ] FY25 User Recertification completed, Data usage per program is projected to the end of PoP, fully occupying all licenses available based on accurate on/offboarding.

**Comment by JJediny** [comment]
@mtaylor-gsa please review for completeness

**Comment by JJediny** [comment]
https://docs.google.com/spreadsheets/d/1y6vfV4z-jyqdLGnzUXvpJMNF48RCdWpo8LbUkkfJM7M/edit

**Comment by JJediny** [comment]
Closing formal report follow up documented here https://github.com/GSA-TTS/tts-tech-operations/issues/1830
