### ISSUE TITLE
Security related static code analysis tooling

### ISSUE THREAD

**Issue by pburkholder** [GSA-TTS/tts-tech-operations#331]
## Background information

This used to be provided by Code Climate. Code Climate has been put forward to security for priority review.

## User stories
As any system owner there is a compliance requirement for an ATO to have security static code analysis performed on the production codebase. There is a need to prepare for alternatives, some of which include:
- https://scan.coverity.com/
- [Running sonarqube on cloud.gov](https://github.com/18F/sonarqube-on-cf) (for either all of TTS or per system).
- Use [DHS's Software Assurance Marketplace (SWAMP)](https://www.mir-swamp.org/)
- Veracode (code.gov past work done to acquire)
- [Semmle formerly](https://LGTM.com) (*acquired by Github - status in their FEDRAMP tailored authorization?) 
- Various standalone libraries for code scanning w/ CI integration examples.

## Implementation steps

- [ ] Follow up with Code.gov team on their past efforts to acquire Veracode
- [ ] Work with Cloud.gov to finalize docs, deployment, and maintenance for sonarqube - https://github.com/18F/sonarqube-on-cf
- [ ] Set up a meeting with DHS about CI integration with MIR-SWAMP
- [ ] Flesh out the list of static code utilities that can be run in docker containers or as part of CI - listing for common programming languages using in TTS.
   - [ ] Golang
   - [ ] Ruby
   - [ ] Python
   - [ ] Javascript (nodejs/typescript)
   - [ ] HTML/CSS
* to a lesser degree
   - [ ] PHP
   - [ ] Java
- [ ] Determine path foward (pending codeclimate ruling)
- [ ] Distinguish between static code analysis and dependency scanning

## Acceptance criteria

- [ ] [Before You Ship](https://before-you-ship.18f.gov/security/static-analysis/) has been updated

**Comment by afeld** [comment]
Closing as duplicate of https://github.com/18F/tts-tech-portfolio/issues/245.

**Comment by afeld** [comment]
On second thought, reopening this as a smaller piece of that larger issue.

**Comment by JJediny** [comment]
**Blocked**
- [ ] awaiting a final determination on codeclimate approval from GSA security
- [ ] receive feedback/review of cloud.gov self-serviced sonarqube option from cloud.gov team.

**Comment by afeld** [comment]
Code Climate has since gotten its ATO; how much is left to do here? Do we want to split out more specific issues?

**Comment by pburkholder** [comment]
Are we in a position to recommend Code Climate as a static code analysis tool within TTS?

**Comment by afeld** [comment]
We already do: https://before-you-ship.18f.gov/security/static-analysis/

**Comment by JJediny** [comment]
Wont fix will coordinate with GSA IT AppSec offering when available
