### ISSUE TITLE
EPIC: TTS dogfooding

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#71]
- [ ] federalist.18.gov
- [ ] cloud.gov
- [x] data.gov
- [ ] code.gov
- [x] search.gov
- [x] ecpic
- [ ] citizenscience.gov
- [x] challenge.gov
- [x] DAP (analytics.usa.gov)
- [ ] api.data.gov
- [ ] feedback.usa.gov (touchpoints TBD service for UX feedback)
- [x] digital.gov
- [x] U.S. Digital Registry
- [x] Federal Government Mobile Apps Directory
- [x] Federal CrowdSource Mobile Testing Program
- [ ] performance.gov
- [ ] USWDS
- [ ] login.gov
- [ ] usa.gov
- [ ] USA.gov Short URLs
- [ ] tailored.fedramp.gov (*how TTS systems can pursue authorization using it)
- [ ] https://methods.18f.gov/
- [ ] https://content-guide.18f.gov/
- [ ] https://plainlanguage.gov/
- [ ] https://accessibility.digital.gov/
*others? (comment)

#### Acceptance Criteria:
- [ ] Update https://digital.gov/services/ with other services (if any).
- [ ] Create a Dogfooding page on TTS Handbook (or Infrastructure page in before-you-ship)
- [ ] Update and link dogfooding page from the Software/Micropurchase page as a pre-check/preferred solution to acquiring.

cc @jeremyzilar are you ok/good with us adding the rest to  https://digital.gov/services ?

**Comment by afeld** [comment]
Such a great list! The closest thing we probably have: https://before-you-ship.18f.gov/infrastructure/

**Comment by gbinal** [comment]
+100

I've always thought that the easiest way to represent this would just be a big table that we manually maintain that shows for each TTS program the list of potential shared services they could be dogfooding.  I took a crack at it a while back here - https://github.com/18F/TTS-Dogfooding/blob/master/dashboard.md

Looks like a few of our colleagues also started up a pass at this here - https://github.com/18F/tts-dogfood cc @adborden

**Comment by annepetersen** [comment]
Depends on your definition of service. Consider:
https://methods.18f.gov/
https://content-guide.18f.gov/
https://plainlanguage.gov/

**Comment by afeld** [comment]
Ah, love the out-of-the-box thinking there, thanks! I suggest we scope "services" to things whose use is objectively verifiable. Might be harder with the ones that don't involve a technical integration, but I bet we can come up with some checks.

**Comment by annepetersen** [comment]
Oh gosh also: https://accessibility.digital.gov/

And yes, understood — but if you want to dogfood everything, we offer more than tech integrations. Just didn't want them all to pass unremarked upon.

**Comment by afeld** [comment]
cc #139

**Comment by afeld** [comment]
https://digital.gov/services/

**Comment by jeremyzilar** [comment]
YES, this is a great list

**Comment by jeremyzilar** [comment]
@JJediny Here is a short list of what we'd need to update/add a service on Digital.gov. Happy to work with you all on getting our page fully updated https://github.com/GSA/digitalgov.gov/wiki/Services-on-Digital.gov

**Comment by afeld** [comment]
[TTS Products and Platforms list](https://docs.google.com/document/d/1vfBiQsprY1m8dG4tS_GeXkhG6ThF5ZqW9JKlDlvbWis/edit?ts=5dcec97a)

**Comment by awichman** [comment]
Historical context above: @AndreaSigz and I created the TTS Products and Platforms list ~2 years ago, so that we'd have an internal resource that was:
- Comprehensive: across the silos; we didn't have other comprehensive lists.
- Easy to maintain: anyone in TTS can search for it/comment/suggest within a product (Gdoc) they use everyday.
- Plain language: the description should be one sentence. 
- Focused: we limited it to products/platforms. There are some services listed now; I think that's fine though I would keep it as tightly scoped as possible. We chose to only list 10x projects that had reached the late phases.

Andrea, chime in if I have missed anything!

**Comment by its-a-lisa** [comment]
I think this [article](https://18f.gsa.gov/2018/03/27/four-benefits-to-using-the-full-TTS-tech-stack/) does a good job depicting an example of dogfooding

**Comment by afeld** [comment]
Keeping this as an epic, but will split out some discrete tasks.

**Comment by afeld** [comment]
[Came up in the Solutions Engineering meeting yesterday.](https://docs.google.com/document/d/1jm5mDHeZQtwulXVtldBU8te7WyeH_MKwNTgoXvGGM7U/edit#bookmark=id.7wgnwt1w2t58)

**Comment by JJediny** [comment]
Closing as this list now existing on https://digital.gov/services/directory/
