### ISSUE TITLE
Utilize compliant event management tools 

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [GSA-TTS/tts-tech-operations#859]
## Background information

Need a tool for event registration management. We've been using EventBrite since it had a ToS review but it never actually went through the IT Standards process to get a VPAT, legal or security review. 

## Implementation Steps

- [x] Fill out WebEx column
- [ ] Determine how marketing will be done
- [ ] Pilot WebEx
- [ ] Provision WebEx accounts
- [ ] Create decision tree / process flow for events at TTS

## Acceptance criteria

- [ ] We have tool(s) identified for event management and teams are ready to migrate to it

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by its-a-lisa-at-work** [comment]
This is kind of Dead on Arrival -- the Eventbrite security team has said flat out that they don't do security reviews. We've tried twice already with no luck. Moving to `Blocked/Watching` and opening a [new issue](https://github.com/18F/tts-tech-portfolio/issues/956) to figure out how to migrate off

**Comment by its-a-lisa-at-work** [comment]
https://gsa-tts.slack.com/archives/CNW3GL70S/p1604591826350800?thread_ts=1604588662.348800&cid=CNW3GL70S

**Comment by josephderosales** [comment]
If the vendor is unwilling to cooperate with a GSA security review, this may be one of those cases where it simply cannot be approved via LiSaaS.

Consulting now with IT Standards if they may know some other option to use Eventbrite via perhaps a waiver of some sort (not sure if this exists).

In the meantime, I will need to get some real-life TTS examples of how they use Eventbrite in order to develop an alternate, workable solution that will meet the needs.

**Comment by josephderosales** [comment]
ZoomGov can satisfy the event/webinar/registration requirements that Eventbrite offers. GSA events should be posted [HERE](https://www.gsa.gov/about-us/events-and-training/gsa-events) 

FAS currently posts events there with the event registration handled by ZoomGov. Will this be a viable solution for TTS to pursue? If so I can reach out to the ZoomGov admin in order to obtain the necessary licenses that will have event registration account privileges.

**Comment by josephderosales** [comment]
Here is an [EXAMPLE](https://gsa.zoomgov.com/webinar/register/WN_w0Kv8n_xTJWnxNiKzyf6pA) of how FAS is handling event/webinar registration via ZoomGov

**Comment by afeld** [comment]
> If the vendor is unwilling to cooperate with a GSA security review, this may be one of those cases where it simply cannot be approved via LiSaaS.

Understood.

> GSA events should be posted HERE

It seems we can/should do that regardless of how registration is handled — check with #event-management if teams can incorporate to their respective processes.

> ZoomGov can satisfy the event/webinar/registration requirements

That has come up before, but ["has limitations"](https://docs.google.com/document/d/1gXLD66RmsUT27-uPkasKFv8i9Q1e3JAvAQTncNkEhas/edit#bookmark=id.2fedmcxuyo4m). I don't know more details, so would check with #event-management about that too.

**Comment by josephderosales** [comment]
Requesting input from the event-management channel:

https://gsa-tts.slack.com/archives/C01H61NDK7E/p1616616041001900

**Comment by josephderosales** [comment]
Reached out to FAS comms division:

Hi Jeremy,

I hope you're doing well and staying safe. I'd like to introduce you to +Kristina Britt - QUC who is with the TTS Outreach Office.

A few TTS programs are currently posting their events/webinars using Eventbrite, which is currently an unapproved tool for use. I've proposed they start posting on the GSA Events page, use ZoomGov, and transition off of Eventbrite.

Vanessa Ussin and Anjaneete Alvardo from GWACs proposed I reach out to you for support. Can you or someone who can provide guidance/assistance please reach out to Kristina so that she can coordinate efforts among the TTS programs affected? Thank you.

+DevOps

**Comment by josephderosales** [comment]
Meeting scheduled next week to go over initial concerns migrating off of Eventbrite:

1. What happens if we need to use another platform or switch from Zoom to WebEx? We've had speakers switch out and not every agency (e.g., DHS) can use Zoom, so we do have to revert back to alternative platforms sometimes with limited notice.

2. What happens if Zoom gets banned again? We had 24 hours to switch all our events last time, so we could luckily still access Eventbrite to email registrants.

3. How do you create custom automated emails in Zoom? The current option is a standard template that only allows for intro, ending, and subject line changes. The bigger issue is that questions regarding the event will be sent to the Zoom host/owner - not a team email address. We need responses to go to a team email. There also is only an option to send 1 email and no reminder emails.

4. Are the custom questions in Zoom more accessible than Eventbrite custom questions (since Eventbrite didn't have the alt text needed to read them)?

**Comment by afeld** [comment]
[Comparison of tools](https://docs.google.com/spreadsheets/d/1yAsMPLtAGxbGSKh5l9njp5-NwETIR62G3-Aq8mq0cN8/edit#gid=0)

**Comment by afeld** [comment]
Changed the title to be more generic. @josephderosales Wanna adjust the top of the issue to reflect current steps? Or we could open a new issue to have a clean start. Up to you.

**Comment by josephderosales** [comment]
Email sent to webmeetings@gsa.gov and Paul Powell - IDTOD <paul.h.powell@gsa.gov> in order to fully populate the [WebEx column](https://docs.google.com/spreadsheets/d/1yAsMPLtAGxbGSKh5l9njp5-NwETIR62G3-Aq8mq0cN8/edit#gid=0)

**Comment by josephderosales** [comment]
response from webmeetings group - will follow up:

Hi Joseph, 

I reached out to our Cisco WebEx representative and he is out of the office today but as soon as he replies back I will get a session set up for you to answer your questions. We have been discussing a periodic AMA style session and this is a great way to get started.

**Comment by josephderosales** [comment]
Reached out to GSA 508 Folks to get more information regarding 508 compliance with WebEx and ZoomGov.


Email sent to:
Section 508 <Section.508@gsa.gov>, Chuck Popelka - IDE <charles.popelka@gsa.gov>, John Sullivan - M1EB <john.j.sullivan@gsa.gov>, Michael Horton - M1ED <michael.horton@gsa.gov>

**Comment by josephderosales** [comment]
WebEx 508 testing scheduled for 3rd wk of Oct. WebEx test event has been created with a registration page. TTS events team has been also designated as co-hosts and panelists.

Working with Dan Perkins from 508.
