### ISSUE TITLE
give feedback on new GEAR

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#938]
## Background Information

The GSA Enterprise Architecture (EA) team demoed the new version of GEAR to the FAS Systems Governance Committee (FSGC). I think the Tech Portfolio explaining the following could help inform the product.

- How we manage [our inventory](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=0)
- How acquisitions relates to the inventory
- How we use other GSA trackers, and how they relate
   - GEAR
   - [Archer](https://before-you-ship.18f.gov/ato/archer/)
   - IT Standards requests in Salesforce
   - [LISaaS In Progress](https://docs.google.com/spreadsheets/d/1MPMrCWfLX5CTVVI8hysUK8DFEKGgGw2L2W-T1jat4LM/edit#gid=1875058589)
- The [open IT Standards data](https://github.com/GSA/data/tree/master/enterprise-architecture)
- How we manage software/integration requests, approvals, and acquisitions

## Implementation Steps

- [ ] Set up meeting with EA team, e.g. Jonah Hatfield and Mark Pratt
- [ ] The EA team has a high-level understanding of TTS' current state of software management

## Acceptance Criteria

- [ ] The EA team has user stories from TTS

**Comment by afeld** [comment]
[Conversation about leveraging Touchpoints for the GSA site inventory](https://gsa-tts.slack.com/archives/CNW3GL70S/p1624490658025500?thread_ts=1624485096.017200&cid=CNW3GL70S), which we should make sure to bring up with the GEAR team to ensure the two play together well.
