### ISSUE TITLE
update Position Description for Alyssa

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [GSA-TTS/tts-tech-operations#942]
[New position description](https://docs.google.com/document/d/1PQ_mqUb9Gx6i5H1v1LciwitMPHp7v-xAynKYMHjrr6U/edit)

## Background Information

The purpose of updating the Position Description is so that Alyssa's CISSP annual fee can be paid for by GSA. By tying the position to different NIST NICE codes that have the training as necessary rather than recommended, it will negate any doubt about the training's applicability and validity. 

## Implementation Steps
- [x] Review and leave comments
- [x] Confirm certification is covered
- [x] @keithrwilson: "work with HR to get the new PD officially created"
- [x] Fill out OF-8
- [x] @its-a-lisa-at-work Fill out PRDS
- [ ] @keithrwilson: "move her onto it"

## Acceptance Criteria

- [ ] Alyssa's position description reflects her current roles and responsibilities

**Comment by its-a-lisa-at-work** [comment]
@afeld do we want to put a Due Date on this? Do you think we should get this resolved this sprint or can it wait until next Sprint?

**Comment by afeld** [comment]
I don't think there's any external time pressure on this. I'll try to get to it after performance reviews (https://github.com/18F/tts-tech-portfolio/issues/807) are done.

**Comment by its-a-lisa-at-work** [comment]
provided responses; tagged @afeld into one
