### ISSUE TITLE
SSL Mate - Decommission

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [GSA-TTS/tts-tech-operations#943]
## Background Information

There are users within TTS who are using SSLMate -- it has been confirmed with GSA IT Security that anybody using SaaS needs to have some sort of Authorization

## Implementation Steps
- [ ] Get in contact with company
- [ ] Provide LiSaaS Solution Profile
- [ ] Company acknowledges Solution Profile
- [ ] Company fills out Solution Profile
- [ ] Company fills out Checklist
- [ ] Company provides Scans
- [ ] Company gets a LiSaaS ATO

## Acceptance Criteria

- [ ] LiSaaS Solution Profile is filled out
- [ ] GSA IT Security issues a LiSaaS ATO
